### ISSUE TITLE
Rascunhos de layouts das telas de SPT

### ISSUE THREAD

**Issue by icarob-eng** [Montaigne-ensaios/montaigne_app#1]
Criar um rascunho com as Activities básicas para a execução e salvamento do ensaio SPT. Não precisa estar em acordo com a identidade visual do projeto, apenas ter todos os componentes do layout que serão usados, para poder servir de base para as outras partes do projeto.

Por favor comentar a lista de layouts que serão implementados e se possível o fluxograma das telas no Figma.

**Comment by JuliaFreire** [comment]
**Layout Básico de componentes**

- [x] Adpter home projetos
- [x] Adpter  Filtro de ensaios 
- [x] Layout Home 
- [x]  Layout Carimbo Def
- 

**Indentificação dos Ids para as telas** 
- [ ] Adpter home projetos
- [ ] Adpter  Filtro de ensaios 
- [ ] Layout Home 
- [ ]  Layout Carimbo Def

**Padronizar os tamanhos dos componentes ( buttons, strings e etc.)**

- [ ] Adpter home projetos
- [ ] Adpter  Filtro de ensaios 
- [ ] Layout Home 
- [ ]  Layout Carimbo Def

**Implementar Temas Day e Night**

1. - Button's Styles 
2. - Strings Styles
3. - EditText Styles
4. -Icons Styles 


Nomeação de activitys, adpter:


1.     home;
2.     carimboDefinitivo;
3.     projeto;
4.     carimboUnico;
5.     ensaio;
6.     furo;

**Comment by JuliaFreire** [comment]
**Adpter Home Projeto** 
(Include no reciclyer )

**Strings**

- Titulo do Projeto 
- Texto de descrição do projeto
- Tipo de ensaio 
- Data de inicio do projeto ( ao clicar em continuação no carimbo automaticamento aparecerá a data de inicio do projeto)


**Imagem** 
- Logo da empresa ou foto de demostração do ensaio;


**Button**
- Button de excluir ensaio ou editar. 

PALETA DE CORES 

#042741



![adpter_home_projetos](https://user-images.githubusercontent.com/89329701/181376208-1f103677-4250-4bd5-be54-eac6ee0bf6de.png)

**Comment by JuliaFreire** [comment]
Push na issue #1 porém falta da include nos reciclyer dos adpters e organizar paleta de cores,icons e cores dos textos, eliminar buttons desnecessários  @icarob-eng

**Comment by nicoled20** [comment]
Links: 
https://www.figma.com/file/y1CuuURgwLfS2sX976B1eZ/Prot%C3%B3tipo-do-Montaingne-2.0
https://www.figma.com/file/1PAwl5jHOV4YgmgD2ZAwSo/Arquitetura-montainegn-2022?node-id=0%3A1

**Comment by JuliaFreire** [comment]
**Adpter Home Filtro de ensaios**
(Include no reciclyer )

**Button com o tipo de ensaio** 

-  ex: Spt, granulometria.

**Imagem**

-  Logo do tipo de ensaio 

**PALETA DE CORES**

- #042741 (Azul )
- #FB0035(Rosa)
- #EAEAEA (Branco)


ANDROID STUDIO
![image](https://user-images.githubusercontent.com/89329701/182730001-2ae3b78c-a74d-4a67-a90e-56f8e6d48db8.png)


FIGMA
![image](https://user-images.githubusercontent.com/89329701/182729924-90c679ef-dc1f-48b6-afad-c56cd12ce24f.png)

Obs. O funcionamento do filtro se dará ao clicar em um button do tipo de ensaio, o usuario   observará a modificação na tela, dada pelo fragment, e aparecerá somente os projetos feitos em spt.

**Comment by JuliaFreire** [comment]
### Acitivity Home 

**Button Flutuante** 
_Adicionar projetos e excluir projetos_

**STRINGS**

- Filtro de ensaios (Auxiliar o adpter visualmente)
- Meus projetos ( auxiliar adpter projetos)

**RECYCLER**

- 1 Recycler do filtro de ensaios 
- 1 FrameLayout para implementar os fragments dos projetos

### 1 tela home 03/08/22

![image](https://user-images.githubusercontent.com/89329701/182737817-ae331e9a-556f-4b24-aa6e-f6fa4e5f8841.png)

**Comment by JuliaFreire** [comment]
### Implementar Layout do Carimbo Definitivo @nicoled20 


**Figma**
![image](https://user-images.githubusercontent.com/89329701/182739996-fcab0768-d776-4745-b8ff-6383f78ab6f1.png)

### TAREFAS

- [ ] Dados do carimbo definitivo (upar projeto antigo do nosso app e pegar os dados da tela de car.definitivo)
- [ ] Campos obrigatorios 
- [ ] Excluir butão Salvar
- [ ] Separar icons para por ao lado do EditText
- [x] Organizar Strings 
- [ ] Separar textos que ira utilizar

**Comment by JuliaFreire** [comment]
<img width="3243" alt="Arquitetura montainegn 2022" src="https://user-images.githubusercontent.com/89329701/183134022-99f5ea3a-3f98-4b94-9763-e5b3c889daa1.png">
Tarefas

**Comment by JuliaFreire** [comment]
### Layout da Tela de projetos

**Strings**

Titulo do projeto

**Button**

Bnt Carimbo 

**Image_button**

Image_button_excluirFuro
Image_button_adcionarFuro

Recycler

Recycler_furo

![image](https://user-images.githubusercontent.com/89329701/183753131-cf5262da-e526-4f05-8e44-868386451c8b.png)
@icarob-eng

**Comment by JuliaFreire** [comment]
TO DO 

Exporta styles

- [ ] EditText
- [ ] Button
- [ ] Strings
- [ ] Images
- [ ] ImgButton
- [ ] Toolbar

Exporta Strings

**Comment by JuliaFreire** [comment]
### Layout da tela de carimbo definitivo


**EditText**

- EditTextNomeProjeto
- 

Buttons

Strings
Imagem
**TextView**



12/08/22
 Print da tela carimbo definitivo 

<img width="3243" alt="Arquitetura montainegn 2022" src="https://user-images.githubusercontent.com/89329701/184405983-30c62e79-d16e-411f-b8e0-402257a1d5dd.png">

**Comment by JuliaFreire** [comment]
### Relatorio das telas básicas do aplicativo (Implementação básica)

 @Josezinn e @JuliaFreire 

Implementado componentes básicos das telas de carimbo defintivo

**GERAL** 

A FAZER
- [ ] Strings para os TextViews
- [ ] Renomear ids
- [ ] Padronizar tamanho dos buttons e componentes
- [ ] Implementar toolbar ( a decidir)
- [ ] String para cada Hint
- [ ] Novos icons

**CARIMBO DEFINITIVO**

**A fazer** 

- [ ] String para cada Hint
- [ ] Renomear ids
- [ ] Strings para os TextViews
- [ ] Novos icons
- [ ] Padronizar tamanho dos buttons e componentes
- [ ] Implementar toolbar ( a decidir)
- [ ] Organizar textView se é obrigatório ou não 
- [ ] Button de voltar (Seta)

![image](https://user-images.githubusercontent.com/89329701/184723872-d5278e86-47e4-4a62-8c6a-81b01fb1ec29.png)

![image](https://user-images.githubusercontent.com/89329701/184723896-2ea73499-24d5-4f6e-bfec-3f8ded6ab8d4.png)


**CARIMBO ÚNICO**


![image](https://user-images.githubusercontent.com/89329701/184751807-1c52c38f-29f7-46ec-ae17-1fc62de8875e.png)

**ENSAIO**

Tela de criação de ensaio 

A fazer

- [ ]  Adicionar icon de visualização de amostras

![image](https://user-images.githubusercontent.com/89329701/184753024-829abee8-023a-4eea-b8a2-272ef9e8db52.png)

**FURO**

Tela com acesso as amostras 

A fazer
- [ ] Implementar toll bar 
- [ ] Implementar adpter de amostras

![image](https://user-images.githubusercontent.com/89329701/184754314-dc3ebcad-6013-4d39-b4d5-e5eb764eed19.png)

**HOME**

Tela principal

_new- adicionado buttonFlutuante de excluir projetos_

Ideia  _Fazer buttonFluante como um menu e por adiciona projetos.

A fazer 
- [ ] Implementar adpter nos recyclers.


![image](https://user-images.githubusercontent.com/89329701/184755189-c69f0f91-3126-41e2-9db4-a3fbcd3c7be3.png)

**PROJETO**

Resumo da tela

Buttons
Adicionar e excluir furos 

Reclycler dos dados do ensaio para ir para o  layout furo.

![image](https://user-images.githubusercontent.com/89329701/184755511-6e20417d-b3c6-41e0-b6a7-8d0a1d14f61f.png)

**ADPTERS**

**Adpter home projeto categoria**

![image](https://user-images.githubusercontent.com/89329701/184755842-bec10c03-3eb5-4eec-a3df-b7e7415c0623.png)

**Adpter home projetos**

![image](https://user-images.githubusercontent.com/89329701/184756059-644b0d44-7ac3-4d1e-8159-fa4e7f603121.png)


**Adpter projeto** 

Adpter para ver o tipo de ensaio 

![image](https://user-images.githubusercontent.com/89329701/184756675-7b819298-5bce-40be-8dd0-b5b1017cf4ba.png)

**Comment by icarob-eng** [comment]
#15 fecha esta issue.
