### ISSUE TITLE
Refatoração de nomes no data_layer

### ISSUE THREAD

**Issue by icarob-eng** [Montaigne-ensaios/montaigne_app#14]
Como padrão nas regras de estilo especificadas em [development_guide.md](https://github.com/Montaigne-ensaios/montaigne_app/blob/main/development_guide.md), deve-se utilizar nomes de classes, variáveis, arquivos e ids por todo o projeto em inglês. Entretanto, para fins de clareza na comunicação de aspectos técnicos do projeto, os seguintes termos técnicos devem ser escritos especificamente da forma demonstrada no código do projeto (não necessariamente como resultado no layout). Os termos estarão especificados em negrito.

A princípio temos o **projeto**, com localidade, responsável e interessado (cliente) e que gera um **relatório definitivo**. O projeto tem diversos **furos**, que podem ter sua própria **cota inicial**, e nível d’água independentes entre si. Cada furo tem diversas **amostras** com sua **profundidade** inicial específica (isto é, a profundidade de onde a amostra é retirada), sendo compostas por 3 **segmentos**, cada uma com sua própria **penetração** (padrão de 15 cm), **golpes**, e caracterização do solo.

Ou seja, por favor utilizar os seguintes termos em português em todas as ocasiões no código:

- Projeto;
- Relatório definitivo;
- Furo;
- Cota inicial;
- Amostra;
- Profundidade;
- Segmento;
- Penetração;
- Golpes;

**Comment by rodrigoCodDev** [comment]
Os nomes foram refatorados no branch data_layer (#20).
Por favor, notificar caso haja algum erro ou correção a se fazer.

Em breve, quando a parte do back-end estiver finalizada, faremos o Pull Request para a branch dev.

**Comment by icarob-eng** [comment]
>  Por favor, notificar caso haja algum erro ou correção a se fazer.

O nome das classes foi alterado, mas os campos e métodos, não. Eles também precisam ser atualizados :(

**Comment by rodrigoCodDev** [comment]
Está sendo corrigido...

**Comment by icarob-eng** [comment]
As modificações estão junto da #25
