### ISSUE TITLE
Integração do layout com o front end

### ISSUE THREAD

**Issue by icarob-eng** [Montaigne-ensaios/montaigne_app#16]
Integrar os layouts vindos de #15 com o código de #10. Isto consiste em popular os adapters, mesmo com mocks e, claro, instanciar as views a partir do layout. Layouts para se integrar:

- [x] `home` (com dois adapters);
- [x] `carimboDefinitivo`;
- [x] `carimboUnico`;
- [x] `ensaio`;
- [x] `furo` (com um adapter);
- [x] `projeto` (com um adapter);

**Comment by icarob-eng** [comment]
Além disso, é necessário refatorar os ids no layout. E fazer os intents no botões e adpaters. Por enquanto pode-se passar apenas strings de mock entre as activities, mas após #2, devera se passar models serializáveis.

**Comment by icarob-eng** [comment]
Como limpar back stack de activities num intent:
```Intent intent = new Intent(this, A.class);
intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK); 
startActivity(intent);
finish();
```

**Comment by JuliaFreire** [comment]
Implementação de icons do aplicativo 


-Logo do app
-Adicionado icon de add projeto

**Comment by icarob-eng** [comment]
Vou pôr os intents no adapter da `home` e nós Adapters de `ensaio` e `projeto`, então @emanuellykarine, faça as telas `carimboDefintivo`, `carimboUnico` e `furo`.

**Comment by icarob-eng** [comment]
@emanuellykarine, o model de `projeto` só vai ser instanciado na tela de carimbo único, quando tiver todos os dados, então passe os dados de `carimboDefintivo` pra `carimboUnico` usando para cada campo:
```java
intent.putExtra(String, String);
```

**Comment by icarob-eng** [comment]
A chamada do método `onCreate()` da `AbstractActivity` não tem funiconado de forma adequada, ele não executa o `initializeViews()`. Talvez seja melhor retirar esta estrutura de nossa arquitetura.

**Comment by icarob-eng** [comment]
> Vou pôr os intents no adapter da `home` e nós Adapters de `ensaio` e `projeto`, então @emanuellykarine, faça as telas `carimboDefintivo`, `carimboUnico` e `furo`.

Perdoe, o correto seria: eu fçao os adapters de `furo` e `projeto` e ti faz os carimbos e `ensaio`.
