### ISSUE TITLE
IDS dos layouts (por na issue #16)

### ISSUE THREAD

**Issue by josefrancisco341** [Montaigne-ensaios/montaigne_app#17]

**Comment by josefrancisco341** [comment]
IDENTIFICAÇÃO "ID" DOS LAYOUTS 


Padrão= Tipo+Função 
Ex: textViewCarimbo


<html><body>


TextView | text_
-- | --
ImageView | image_
Button | button_
Menu | menu_


</body>
</html>

**Comment by josefrancisco341** [comment]
### CARIMBO DEFINITIVO 

ID: BUTTONS


** ID: IMAGENS**
1. iconContato;
2. iconReferenciaDeNivel;
3. iconEdit;
4. iconCamera;
5. iconEmpresa;

**Comment by josefrancisco341** [comment]
### CARIMBO DEFINITIVO
@Josezinn entrega até 21/08
**ID: Button**

buttonContinueCarimbo

**ID: ImageButton**

imageButtonHome
imageButtonPhoto

imageButtonHelpNameProjeto
imageButtonHelpTecnico
imageButtonHelpEmpresa
imageButtonHelpContato
imageButtonHelpCliente
imageButtonHelpLocalObra
imageButtonHelpQuantidadeFuros
imageButtonHelpReferenciaNivel

**ID: TextView**

textWarning1
textWarning2
textObligatoryWarning

textNameProjeto
textTecnico
textEmpresa
textContato
textCliente
textLocalObra
textQuantidadeFuros
textReferenciaNivel


**ID: EditText**

editTextNameProjeto
editTextTecnico
editTextEmpresa
editTextContato
editTextCliente
editTextLocalObra
editTextQuantidadeFuros
editTextReferenciaNivel

**ID: Image**

imageProfile

@nicoled20

**Comment by JuliaFreire** [comment]
### Fazer ids na issue #16

**Comment by JuliaFreire** [comment]
**CARIMBO ÚNICO**
@Josezinn entrega até 21/08
**ID: Button**

buttonStartEnsaio
buttonGetLocation

**ID: ImageButton**

imageButtonHome

imageButtonHelpStartDate
imageButtonHelpNivelFuro
imageButtonHelpCoordenadaFuro

**ID: TextView**

textWarningObrigatory

textStartDate
textNivelFuro
textCoordenadasFuro

**ID: EditText**

editTextStartDate
editTextNivelFuro

**Comment by JuliaFreire** [comment]
**ENSAIO**
@nicoled20 entrega até 21/08
**ID: Button**

buttonFinishFuro

**ID: ImageButton**

imageButtonHome

imageButtonHelpNivelAgua

imageButtonDecrementGolpe1
imageButtonIcrementGolpe1
imageButtonDecrementGolpe2
imageButtonIcrementGolpe2
imageButtonDecrementGolpe3
imageButtonIcrementGolpe3

**ID: TextView**

textProfundidade
textAmostraN
textGolpes
textPenetracao
textNivelAgua
textSegmento 

**ID: EditText**

editTextProfundidade
editTextNivelAgua

editTextGolpe1
editTextGolpe2
editTextGolpe3
editTextPenetracao1
editTextPenetracao2
editTextPenetracao3

**Comment by JuliaFreire** [comment]
### PROJETO
@nicoled20 entrega até 21/08
**ID: Button**

buttonCarimbo

**ID: ImageButton**

imageButtonAddFuro
imageButtonDeleteFuro

**ID: TextView**

textFuro

**ID: Recycler**

recyclerFuro

**Comment by JuliaFreire** [comment]
### FURO
@nicoled20 entrega até 21/08
**ID: Button**

buttonPrint

**ID: ImageButton**

imageButtonAddAmostra
imageButtonDeletAmostra

**ID: TextView**

textAmostra

**ID: Recycler**

recyclerAmostra

**Comment by icarob-eng** [comment]
@JuliaFreire, por favor, lembrar de pôr palavras que não dizem respeito ao ensaio, como adicionar ou deletar, em inglês. Como no caso de buttonAdicionarFuro, o certo seria, buttonAddFuro.

**Comment by icarob-eng** [comment]
@JuliaFreire rever nomeação dos layouts de adapters. O `adapter_projeto.xml` por exemplo, não tem um nome esclarecedor, uma vez que ele adapta furos. E talvez você queira copiar ele e criar um layout de adapter para amostras também.
