### ISSUE TITLE
Implementação dos styles nos layouts

### ISSUE THREAD

**Issue by JuliaFreire** [Montaigne-ensaios/montaigne_app#19]
**Toolbars a incrementar.**

- [x] 1. home;
- [x] 2. carimboDefinitivo;
- [x] 3. projeto;
- [x] 4. carimboUnico;
- [x] 5. ensaio;
- [x] 6. furo;

**Icons a adicionar**

icon_edit
icon_perfil
icon_empresa
icon_contato
icon_local
icon_save
icon_ajuda
icon_excluir
icon_adicionar

**Comment by JuliaFreire** [comment]
Mensagens de campo indicando que estar vazio (Incluindo dentro do EditText que estiver)

Mensagens de Interrupções do ensaio

@nicoled20 @Josezinn e @JuliaFreire 


DATA ENTREGA: 26/08/22

**Comment by JuliaFreire** [comment]
Adicionar interações das telas ( buttons)
- [ ] Voltar

**Comment by JuliaFreire** [comment]
Adiciona Styles de Button


Buttons Styles
- [x] Button Padrão do app
- [x] Button Flutuante
- [x] ImageButtons 
- [ ] Adiciona icons
- [ ] Toolbars

**Comment by JuliaFreire** [comment]
Implementado EditText  Style no aplicativo ( a revisar em uma reunião)

**
![image](https://user-images.githubusercontent.com/89329701/191640004-5b86834a-c63d-4154-a8d1-2e6956600614.png)
**

**Comment by JuliaFreire** [comment]
![Uploading image.png…]()



Revisa nomeação do button continuação

**Comment by JuliaFreire** [comment]
![Uploading image.png…]()



Revisa nomeação do button continuação

**Comment by JuliaFreire** [comment]
![Uploading image.png…]()



Revisa nomeação do button continuação

**Comment by JuliaFreire** [comment]
![Uploading image.png…]()



Revisa nomeação do button continuação

**Comment by JuliaFreire** [comment]
![Uploading image.png…]()



Revisa nomeação do button continuação

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/192373791-f647dd2b-0e8d-4c15-9485-783786d31358.png)
Adicionado material design

**Comment by JuliaFreire** [comment]
### Implementar textImputLayout para substituir o editext 

TextImputLayout 





**Implementar ImputLayout com campo obrigatório**

_Função: TextimputLayout Simples_ 

Aviso: substituir campos como:
- app:startIconDrawable="@drawable/icon_home3"
- app:helperText="*obrigatório"

Código para copiar:

    <com.google.android.material.textfield.TextInputLayout
        style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:startIconDrawable="@drawable/icon_home3"
        app:helperText="*obrigatório"

        app:helperTextTextColor="@color/destaque"
        android:layout_marginStart="1dp"
        android:layout_marginEnd="1dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        tools:layout_editor_absoluteY="111dp">

        <com.google.android.material.textfield.TextInputEditText
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:hint="hint" />
    </com.google.android.material.textfield.TextInputLayout>

![image](https://user-images.githubusercontent.com/89329701/192406605-5c64c1a9-36ac-4928-8c67-0d94d63c8843.png)
**Image exemplo**


TextImputLayout com icon de apagar oque escreveu 

     <com.google.android.material.floatingactionbutton.FloatingActionButton
          android:id="@+id/fabNewProjeto"
          android:layout_width="wrap_content"
          android:layout_height="wrap_content"
          android:layout_marginEnd="20dp"
          android:layout_marginBottom="20dp"
          android:src="@drawable/icon_adicionar"
          app:elevation="20dp"
          app:fabSize="normal"
          app:layout_constraintBottom_toBottomOf="parent"
          app:layout_constraintEnd_toEndOf="parent" />
      <com.google.android.material.textfield.TextInputLayout
          style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
          android:layout_width="match_parent"
          android:layout_height="wrap_content"
          android:layout_marginStart="1dp"
          android:layout_marginEnd="1dp"
          app:counterMaxLength="2"
          app:counterEnabled="true"
          app:endIconMode="clear_text"
          app:helperText="*obrigatório"
          app:helperTextTextColor="@color/destaque"
          app:layout_constraintEnd_toEndOf="parent"
          app:layout_constraintStart_toStartOf="parent"
          app:layout_constraintTop_toTopOf="parent"
          app:startIconDrawable="@drawable/icon_home3">
  
          <com.google.android.material.textfield.TextInputEditText
              android:layout_width="match_parent"
              app:counterMaxLength="2"
              android:layout_height="wrap_content"
              android:hint="hint" />
      </com.google.android.material.textfield.TextInputLayout>
  

![image](https://user-images.githubusercontent.com/89329701/192543448-3dda6dcf-b3d0-43ff-b98a-6aafeee89680.png)



Para informar qual tipo de texto do imput ( android:inputType="phone")

    <com.google.android.material.textfield.TextInputEditText
            android:layout_width="match_parent"
            **android:inputType="phone"**
            app:counterMaxLength="2"
            android:layout_height="wrap_content"
            android:hint="hint" />
    </com.google.android.material.textfield.TextInputLayout>


Limite o campo a caracteres
Adicionar 

     <com.google.android.material.textfield.TextInputLayout
            app:counterMaxLength="2" (Substitute)
            app:counterEnabled="true"
      
            <com.google.android.material.textfield.TextInputEditText
         
                android:maxLength="2"
               
        </com.google.android.material.textfield.TextInputLayout>

![image](https://user-images.githubusercontent.com/89329701/192547749-21cf1968-3771-4653-96f8-1d503e579389.png)

**Comment by JuliaFreire** [comment]
**Indicação de erro no campo** 

    <com.google.android.material.textfield.TextInputLayout
            style="@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginStart="1dp"
            android:layout_marginEnd="1dp"
    
            app:errorEnabled="true"
            app:errorIconDrawable="@drawable/ic_aviso"
            app:counterMaxLength="2"
            app:counterEnabled="true"
            app:endIconMode="clear_text"
            app:helperText="*obrigatório"
            app:helperTextTextColor="@color/destaque"
    
    
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:startIconDrawable="@drawable/icon_home3">
    
            <com.google.android.material.textfield.TextInputEditText
                android:layout_width="match_parent"
                android:inputType="phone"
                android:layout_height="wrap_content"
                android:hint="hint" />
        </com.google.android.material.textfield.TextInputLayout>

**No java** 

       binging.textInputEditText.doOnTextChanged { text, start, before, count ->
            if (text!!.length > 0) { binding.textInputLayout.error = "Muito!"
            } else if (text.length <10)
            {
            binding.textInputLayout.error = null
            }
        }
![image](https://user-images.githubusercontent.com/89329701/192552946-68f756a7-ecaf-48de-81da-929182bcc848.png)

**Comment by JuliaFreire** [comment]
@Josezinn 

Vamos substitutir os editText para TextImputLayout 

Se você puder depois importar os icons bonitinhos para o app agradeço irei lhe mandar em breve
]

**Comment by JuliaFreire** [comment]
Custominar cores do imputLayout 

![image](https://user-images.githubusercontent.com/89329701/192555185-fe18903d-7b89-4134-8a8f-9ac7aef029bf.png)

**Comment by JuliaFreire** [comment]
Exemplo  de oque digitar no textImputLayout
![image](https://user-images.githubusercontent.com/89329701/192555349-4ccd82ce-8161-42a8-9ba3-311ee5bdd564.png)


video: https://youtu.be/q-DnUKbGsgA

**Comment by JuliaFreire** [comment]
### Exportation de icons

Driver com icons a organizar e renomear:

https://drive.google.com/drive/u/1/folders/1Cb1hEU8uFWSFymalQPfcG2sqeMnsHTVL

Obs: Importar somente os icons que faltam para o aplciativo observar as telas e ver quais necessitam, se for salvar do figma por em svg a qualidade fica melhor.

Tamanho padrão de icons

32px icons normais 

24px - Para icons que estão dentro de algum objeto exemplo: ao lado de um ImputLayout ou editText

**Nomes dos icons para renomear:**

     

- [ ]       icon_edit
- [x]       icon_photo
- [x]       icon_profile
- [ ]       icon_empresa
- [ ]       icon_contato
- [ ]       icon_localization
- [ ]       icon_save
- [ ]       icon_help
- [x]       icon_delet
- [x]       icon_add
- [x]       icon_button_add



![image](https://user-images.githubusercontent.com/89329701/192593894-c47de547-c7f7-4b41-9181-0338cc5e4dde.png)



DICAS:

Sites para encontrar icons 

  https://www.flaticon.com/search?word=technique&order_by=4
  https://www.iconfinder.com/search?q=save


@nicoled20

**Comment by JuliaFreire** [comment]
Resumo de atividade feitas 

- Renomeado ids para ingles
- Excluido icons do app 
- Adicionar icons renomeados
- Exportado styles de text e button

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/194586465-70543e6d-89eb-4063-b5b9-424cec919103.png)


Adicionado icons da tela home

**Comment by JuliaFreire** [comment]
Exportado icons do app e adicionado as telas Home,Furo,Carimbo Definitivo, Carimbo Unico, Ensaio e Projeto

Icons adicionados

![image](https://user-images.githubusercontent.com/89329701/194615403-01e18daf-f70b-439a-a182-11438072fb3b.png)

**Comment by JuliaFreire** [comment]
Finalização issue 19


- [ ] Modo Noturno 
- [ ] Implementado icons novos nas telas
- [ ] Adicionado Style do editText e button
- [ ] Organizado constraint
- [ ] Selecionado paleta do aplicativo

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/196273246-6011219f-d426-4796-9d51-82f3af83ddb1.png)
 
adicionado modo noturno ao aplicativo

**Comment by JuliaFreire** [comment]
<style name="Theme.MontaigneApp" parent="Theme.AppCompat.Light.NoActionBar">



        
        <item name="colorPrimary">#336E99</item>
        <item name="colorPrimaryVariant">@color/black</item>
        <item name="colorOnPrimary">@color/white</item>


        
        <item name="android:textColor">@color/black</item>
        <item name="colorAccent">@color/accent</item>
        //fundo
        <item name="android:windowBackground">#FFFFFF</item>

        <item name="android:textColorHint">@color/hint</item>
        <item name="materialButtonStyle">@style/ButtonPadrao_light</item>
        <item name="imageButtonStyle">@style/ImageButton_light</item>
        <item name="textInputStyle">@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox</item>
        <item name="editTextStyle">@style/Edit_Text_light</item>
        <item name="android:drawable">@style/imageView_Dark</item>





        
        <item name="colorSecondary">@color/color_primary</item>

        
        <item name="colorOnSecondary">@color/white</item>


        
        <item name="android:statusBarColor" tools:targetApi="l">@color/color_primary</item>

        
    </style>

    <style name="Theme.MontaigneApp.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>

    <style name="Theme.MontaigneApp.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />

    <style name="Theme.MontaigneApp.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />




</resources>

**Comment by JuliaFreire** [comment]
<style name="Theme.MontaigneApp" parent="Theme.AppCompat.Light.NoActionBar">
        
        
        
                
                <item name="colorPrimary">#336E99</item>
                <item name="colorPrimaryVariant">@color/black</item>
                <item name="colorOnPrimary">@color/white</item>
        
        
                
                <item name="android:textColor">@color/black</item>
                <item name="colorAccent">@color/accent</item>
                //fundo
                <item name="android:windowBackground">#FFFFFF</item>
        
                <item name="android:textColorHint">@color/hint</item>
                <item name="materialButtonStyle">@style/ButtonPadrao_light</item>
                <item name="imageButtonStyle">@style/ImageButton_light</item>
                <item name="textInputStyle">@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox</item>
                <item name="editTextStyle">@style/Edit_Text_light</item>
                <item name="android:drawable">@style/imageView_Dark</item>
        
        
        
        
        
                
                <item name="colorSecondary">@color/color_primary</item>
        
                
                <item name="colorOnSecondary">@color/white</item>
        
        
                
                <item name="android:statusBarColor" tools:targetApi="l">@color/color_primary</item>
        
                
            </style>
        
            <style name="Theme.MontaigneApp.NoActionBar">
                <item name="windowActionBar">false</item>
                <item name="windowNoTitle">true</item>
            </style>
        
            <style name="Theme.MontaigneApp.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />
        
            <style name="Theme.MontaigneApp.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />
        
        
        
        
        </resources>

**Comment by JuliaFreire** [comment]
<resources xmlns:tools="http://schemas.android.com/tools">
                
                <style name="Theme.MontaigneApp" parent="Theme.AppCompat.DayNight.NoActionBar">
                    
                    <item name="android:colorPrimary">@color/destaque</item>
                    <item name="colorPrimaryVariant">@color/fundo</item>
                    <item name="colorOnPrimary">@color/white</item>
                    <item name="android:windowBackground">@color/black</item>
            
            
                    
                    <item name="android:textColor">@color/white</item>
                    <item name="colorAccent">@color/accent</item>
                    //fundo
                    <item name="backgroundColor">#000000</item>
            
                    <item name="android:textColorHint">@color/material_dynamic_neutral_variant50</item>
                    <item name="materialButtonStyle">@style/ButtonPadrao_Dark</item>
                    <item name="imageButtonStyle">@style/ImageButton_Dark</item>
                    <item name="textInputStyle">@style/Widget.MaterialComponents.TextInputLayout.OutlinedBox</item>
                    <item name="editTextStyle">@style/Edit_Text_dark</item>
                    <item name="color">@color/destaque</item>
            
                    
                    <item name="colorSecondary">@color/destaque</item>
            
                    
                    <item name="colorOnSecondary">@color/white</item>
            
            
            
                    <item name="android:statusBarColor" tools:targetApi="l">@color/black</item>
                    
                </style>
            
            
                <style name="Theme.MontaigneApp.NoActionBar">
                    <item name="windowActionBar">false</item>
                    <item name="windowNoTitle">true</item>
                </style>
            
                <style name="Theme.MontaigneApp.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />
            
                <style name="Theme.MontaigneApp.PopupOverlay" parent="ThemeOverlay.AppCompat.Dark" />
            
            
            </resources>

**Comment by marmundo** [comment]
@JuliaFreire A validação dos campos não está acontecendo. Os campos obrigatórios não são obrigatórios na criação do ensaio.

Além disso, os ícones de nomes em alguns campos estão errados parecem um calendário.

Além disso, não há máscara para datas nem telefone no formulário.

Eu alterei o label do botão continuação para próximo.

Amanhã eu quero repassar as telas com vc. Por favor não falte.

**Comment by JuliaFreire** [comment]
@marmundo prof essa organização iremos fazer na nova versão dos fragments devido que iremos implementar os imputlayout ao invés do edittext, a questão dos icons e campos obrigatorios iremos corrigir exatamente kk nessa nova versão, eu havia feito o pull request irei fazer novamente ent para incluir essas suas atualizações

**Comment by marmundo** [comment]
> @marmundo prof essa organização iremos fazer na nova versão dos fragments devido que iremos implementar os imputlayout ao invés do edittext, a questão dos icons e campos obrigatorios iremos corrigir exatamente kk nessa nova versão, eu havia feito o pull request irei fazer novamente ent para incluir essas suas atualizações

ok. Amanhã você me explica ;)

**Comment by icarob-eng** [comment]
> @JuliaFreire A validação dos campos não está acontecendo. Os campos obrigatórios não são obrigatórios na criação do ensaio.
 
> Além disso, não há máscara para datas nem telefone no formulário.

@marmundo o objetivo desta isssue era criação de styles. A branch acabou abarcando também ícones e o modo noturno, por disponibilidade de tempo, como descrito em #43. Validação e máscaras de campos não foi pensada para ser feita neste momento, só na próxima milestone e também não seria responsável pela equipe de layout, mas sim a de front end.
