### ISSUE TITLE
Estruturação dos dados a partir de Models

### ISSUE THREAD

**Issue by icarob-eng** [Montaigne-ensaios/montaigne_app#2]
Construção das classes Models necessárias para armazenar os dados do projeto. Pode-se listar nos comentários como ficará a estrutura de dados para melhor acompanhamento do progresso.

**Comment by rodrigoCodDev** [comment]
Os models (modelos) do banco de dados estão sendo definidos no pacote [data](https://github.com/Montaigne-ensaios/montaigne_app/tree/data_layer/app/src/main/java/com/montaigne/montaigneapp/data).

É de vital importância que tanto o planejamento do banco de dados SQLite (@ThiagoAlvesRibeiro ) quanto o do banco de dados do Firebase (@joao-victor-f ) estejam sendo construídos em conjunto. 

Temos que, de forma geral, saber como fazer essa integração entre esses bancos. O model representa os dados que iremos passar e recuperar, então temos que ter um certo cuidado e definirmos duas coisas no model:
- Quais serão os atributos que haverão em cada classe; e
- Qual o tipo dos atributos dessas classes.

Quero que vocês (@ThiagoAlvesRibeiro e @joao-victor-f ) pesquisem como elaborar o DAO e esses models, para posterior discussão e conclusão dessa issue. Estarei ajudando vocês.

**Comment by rodrigoCodDev** [comment]
Os DAOs locais do SQLite estão sendo feitos com [Sugar ORM](https://satyan.github.io/sugar/)

Os Data Sources locais já estão sendo desenvolvidos por @ThiagoAlvesRibeiro .

O DAO para acesso e manipulação dos dados de forma remota está ainda em desenvolvimento por parte de @joao-victor-f . Ao final de sua pesquisa, pretendemos nos reunir e concretizar definitivamente as Models e a forma (atributos, seus tipos...) como iremos armazenar os dados do ensaio.

Previamente, temos uma ideia de como os Models podem estar presentes para o caso do SQLite, mas creio que teremos um árduo desafio pela frente ao tentarmos agregar essas duas tecnologias (SQLite e Firebase) nos Repositories.

**Comment by rodrigoCodDev** [comment]
@joao-victor-f nos mostrou que existe um mecanismo de persistência de dados no Firebase. Isso facilitará muito a implementação, porque a partir disso faremos o armazenamento de dados localmente e remotamente usando apenas essa tecnologia.

Estamos pesquisando e desenvolvendo métodos para gerenciar esse armazenamento e buscando a melhor forma de gravar esses dados no Firebase, ajustando, assim, alguns atributos dos models.

O desenvolvimento em SQL, nesta semana, foi desconsiderada graças a isso. Estamos tentando focar no Firebase com NoSQL.

Entretanto, consideramos que foi algo proveitoso para equipe explorar alguns conceitos sobre SQL e SQLite durante este tempo, certamente nos possibilitou a ter além de um conhecimento sobre essas tecnologias, uma analise mais critica sobre o uso e o papel delas em um aplicativos.

**Comment by rodrigoCodDev** [comment]
Foi feito o Pull Request da branch #2, que continham alguns ajustes do model, com a branch dev.
As mudanças feitas na #2 foram também incluídas na branch de data_layer em que estamos desenvolvendo o banco de dados Firebase.

Futuramente, pretende-se fazer alguns ajustes de acordo com as mudanças que ocorrerão no desenvolvimento do banco de dados.
