### ISSUE TITLE
Permanência básica

### ISSUE THREAD

**Issue by icarob-eng** [Montaigne-ensaios/montaigne_app#25]
Integração dos casos de uso com o front-end, permitindo salvamento do projeto com seu carimbo simples e talvez algumas amostras.

Não é necessário fazer leitura ou qualquer tipo de atualização.

**Comment by icarob-eng** [comment]
Permanência feita para dados de um novo projeto, criando um novo furo e uma nova amostra, e fazendo uso dos casos de uso disponíveis.

**Comment by icarob-eng** [comment]
@joao-victor-f  ou @rodrigoCodDev, por favor verifiquem se o salvamento citado no comentário anterior está funcionando adequadamente no firebase, para podermos marcar como finalizado. Não precisam usar testes automatizados.

**Comment by rodrigoCodDev** [comment]
@icarob-eng , infelizmente, não estamos usando testes automatizados ainda, mas precisando testar.

O código não está sendo compartilhado entre a gente, eu desenvolvi uma parte dele e @joao-victor-f está desenvolvendo a outra, que é relacionada aos testes. Eu estou acompanhando isso, vendo que operações estão prontas para ser utilizadas e aquelas que ainda precisam de algum tipo de ajuste, também dando uma base de ideias para o desenvolvimento dos mesmos. 

As operações de inserção e deleção estão prontas, mas as outras estão em fase de teste.

**Comment by icarob-eng** [comment]
Então a utilização de inserção no branch #25 tá pronta?

**Comment by rodrigoCodDev** [comment]
Não. Pelo que estou constando aqui, para que seja possível o ideal desenvolvimento do projeto e execução dos testes com UI, é preciso implementar algumas correções e mudanças:

- [ ] Usar intefaces como Map e List;
- [ ] Definir campos do model ProjetoSPT (inserir ou deletar): coordenadas (colocar local?), quantidade de furos (necessario?), referencia de nível (aqui?), descrição (colcar?);
- [ ] Verificar outras models;
- [ ] Verificar dinâmica das VM (de que forma os dados estão sendo pegos da activity?);
- [ ] Verificação da linguagem (português ou inglês?) e tradução de termos em todo código;
- [ ] Validação sobre uso das intents (seria bom substituir pelo próprio objeto ao invés de passar todos os dados);
- [ ] Revisão da formatação do código;
- [ ] Refazer usecases perdidos com o merge;
- [ ] Checar os usecases (são necessários? é necessário colocar sufixo?); e
- [ ] Validar update e read de projetos do Firebase.

ISSO É NECESSÁRIO PARA SABER SE DE FATO NA TELA DE CADASTRO DO PROJETO ("CARIMBO") ESTÁ DE FATO SENDO SALVO UM NOVO PROJETO COM TODOS OS DADOS REQUERIDOS ALÉM DE ORGANIZAR MAIS O CÓDIGO. 

Para que eu consiga chegar a tela de cadastro, eu preciso passar pela tela de leitura, ou seja, preciso que o read esteja funcionando e a dinâmica da UI também. 
Para que eu possa salvar o projeto de fato, eu preciso que todos os dados dele estejam padronizados e que os usecases estejam funcionando.

Precisamos nos reunir para discutir esses pontos e como implementar. @icarob-eng e @joao-victor-f 

Algumas correções já estão sendo feitas...

**Comment by icarob-eng** [comment]
A operação de inserção já está implementada na branch #25. O resto do CRUD será feito na mesma branch.
