### ISSUE TITLE
Interfaces de Repositories e Data Source

### ISSUE THREAD

**Issue by icarob-eng** [Montaigne-ensaios/montaigne_app#3]
A partir da issue #2, planejar quais serão os repositories e data sources usados no projeto e em seguida escrever interfaces abstratas para a implementação das classes para diferentes data sources. É recomendado descrever o que será feito nos comentários desta issue, bem como documentar nas interfaces seus usos, por meio de comentários.

**Comment by rodrigoCodDev** [comment]
Link do Figma:
[Montaigne UML](https://www.figma.com/file/TEMtiVQXF47Sq5P2SilHIi/Montaigne-UML?node-id=0%3A1)

**Comment by rodrigoCodDev** [comment]
As interfaces já estão sendo preparadas e colocadas na branch [data_layer](https://github.com/Montaigne-ensaios/montaigne_app/tree/data_layer).

Entretanto, ainda há algumas mudanças a serem definidas no banco e alguns métodos a serem incorporados na interface.

Nossa principal fonte de inspiração nesse trabalho está sendo o trabalho [architecture-samples](https://github.com/android/architecture-samples) fornecido pela Google.

--- 

Solicito um esclarecimento por parte de @JuliaFreire , @icarob-eng e da equipe destinada a pesquisa das normas em relação a entrada de dados para revisão da estrutura do banco de dados de SPT. Caberá a @ThiagoAlvesRibeiro ter esse esclarecimento e tentar fazer as correções no SQL necessárias para o SQLite e comentar com a equipe sobre as mudanças.

Também atribuo essa discussão a @joao-victor-f , que ficou responsável por pesquisar sobre um possível DAO para Firebase. Pois é necessário revisar sobre os tipos de dados que serão colocados nos models. Em relação a isso, deixo aqui minha preocupação em relação a alguns objetos como atributos de classe (se poderão ser armazenados); e ao id (se será definido como String ou Long).

**Comment by rodrigoCodDev** [comment]
Para uma melhor manutenção e criação do banco de dados, decidimos optar pela criação do banco de dados e do DAO das classes usando ORM (Object Relational Mapper).

O que estamos até o momento é o [Sugar ORM](https://satyan.github.io/sugar/). @ThiagoAlvesRibeiro começou a implementar algumas partes no project do SPT. Sendo assim, começa-se a dar uma maior valorização ao desenvolvimento dos Data Sources locais.

Em relação as interfaces, ao qual este tópico se destina, é necessário fazer algumas correções e adaptações nas interfaces, que já estão em discussão na equipe.

**Comment by rodrigoCodDev** [comment]
Começamos a usar o Firebase para estruturarmos o back-end. Foi concordado na reunião que nesse tipo de implementação se seguiria uma estrutura mais simples, baseada em usos de casos (usecases).

Dessa forma desenvolvemos um tipo de DAO para manipularmos os dados com Firebase e faremos os usecases invés de gerar os repositories e data source's.

Entretanto, essa estrutura inicial ainda segue em aberto por @ThiagoAlvesRibeiro que estará desenvolvendo uma alternativa ao Firebase com SQLite.

**Comment by icarob-eng** [comment]
@rodrigoCodDev, como movemos para useCases, devemos fechar essa issue?
