### ISSUE TITLE
Organização por fragments

### ISSUE THREAD

**Issue by icarob-eng** [Montaigne-ensaios/montaigne_app#37]
A maioria das telas exceto a home podem ser passadas para uma única activity, mantendo os botões de navegação (home e próxima tela, ou carimbo) na barra inferior e o conteúdo em si seria em fragments, com botões para manipular o conteúdo (por exemplo lixeria e novo) dentro do próprio fragment e fora da barra de navegação.

Projetar um recycler para a tela de carimbo defintivo, em que os campos de texto sejam reaproveitados e as mensagens sobrescritas.

**Comment by JuliaFreire** [comment]
### Fragments 

https://www.androidpro.com.br/blog/desenvolvimento-android/fragments/
![image](https://user-images.githubusercontent.com/89329701/194182098-b25bf03e-2af6-4e1e-9a3b-b584a5667b2d.png)
![image](https://user-images.githubusercontent.com/89329701/194182234-f383aaaf-d4d7-4caf-8931-573d1a4fdaa6.png)


As subclasses mais comuns utilizadas são, por exemplo, 



Forma visual 


  <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:tools="http://schemas.android.com/tools">
      <fragment
          android:id="@+id/mainFragment"
          android:layout_width="match_parent"
          android:layout_height="match_parent"
          class="br.com.androidpro.meuapp.MainFragment"
          tools:layout="@layout/main_fragment">
      </fragment>
  
  </LinearLayout>

**Comment by icarob-eng** [comment]
Além das questões dos fragments, é importate lembrar sobre os adapters: o layout de um adapter não pode ser um `ConstraintLayout`. Pode-se usar um `LinearLayout` ou mesmo um `RelativeLayout` se preferir.

**Comment by icarob-eng** [comment]
Deve-se terminar de implementar todas as funcionalidades do banco de dados nesta issue.

**Comment by icarob-eng** [comment]
Os fragments podem ser colocados em cima de um `FragmentConteinerView`, [segundo a documentação Android](https://developer.android.com/guide/fragments/create#add-programmatic)

```xml
<!-- res/layout/example_activity.xml -->
<androidx.fragment.app.FragmentContainerView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/fragment_container_view"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />
```

**Comment by JuliaFreire** [comment]
TAREFAS 

- [x] Renomear telas que serão fragments
- [ ] Organizar ImputLayout





Observações #dev

- Buttons pequenos 
- icons desaparecendo

**Comment by JuliaFreire** [comment]
### Tarefas

### 1 Passo 
- [x] Renomear as activity para fragments

  1. CarimboDefinitivo
  2. Carimbo Unico
  3. Furo
  4. Ensaio
  5. Projeto
Obs: _Tela Home e uma nova tela de spt e de granulometria serão activitys_
Adpters serão fragments também

### 2 Passo

- [x] Criar tela spt e granulometria 
- [ ] Animação do button flutuante
- [ ] Criar menu 
- [x] Mudar nome do button do carimbo definitivo para continuar
- [ ]  Criar tela de login


Data de entrega  07/11

**Comment by JuliaFreire** [comment]
https://developer-android-com.translate.goog/guide/fragments/create?_x_tr_sl=auto&_x_tr_tl=pt&_x_tr_hl=pt

**Comment by JuliaFreire** [comment]
Passos para fazer um fragment


Renomear
Tranforma em Frame layout
Criar um constraint

**Comment by icarob-eng** [comment]
@JuliaFreire, quando for refazer as telas de carimbo, ponha os `TextInputLayout`s em um `adapter`, para não ter que refazer tantos `editText`s. Assim é só descrever aqui a lista de inputs e imagens que precisam ser adaptados no `recycler`

**Comment by JuliaFreire** [comment]
Alterar tema 

    <style name="Theme.MontaigneApp" parent="Theme.MaterialComponents.Light.NoActionBar">

**Comment by icarob-eng** [comment]
Renomear: `CarimboDefinitivo` para `CarimboProjeto` e

 `CarimboUnico` para `CarimboEnsaio`.

**Comment by icarob-eng** [comment]
Lembrar de checar se os adapters estão usando `ConstraintLayout`. Eles devem usar outro mais simples como o  `RelativeLayout` ou de preferência o `LinearLayout`. Isto por questões de performance.

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/198128484-d5ac0370-d5e4-4276-b64e-f18feb2cb717.png)


Comit com renomeação dos fragments

@icarob-eng  revisar

**Comment by JuliaFreire** [comment]
comitt de conversão de constraint layout para relative layout adpters

**Comment by icarob-eng** [comment]
> @icarob-eng revisar

Estes erros foram causados por não se ter sido feito sync do gradle pelo problema com o plugin.

**Comment by icarob-eng** [comment]
# Estrutura de uma classe Fragment:
``` java
public class BlankFragment extends Fragment {

    private static final String ARG_PARAM1 = "param1";   // String de nome do parâmetro
    private static final String ARG_PARAM2 = "param2";

    private String mParam1;
    private String mParam2;

    public BlankFragment() {
        // Required empty public constructor
    }

    public static BlankFragment newInstance(String param1, String param2) {
        BlankFragment fragment = new BlankFragment();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, param1);
        args.putString(ARG_PARAM2, param2);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_blank, container, false);
    }
}
```

Para instanciar o `Fragment`, é usado o método `newInstance()` ao invés do construtor, este que deve ficar vazio. Isto serve para facilmente recuperar valores pelo `Bundle` `savedInstanceState`, uma forma de permanência que  permite salvar apenas serializáveis e são salvos no `Bundle`. Como não iremos usar este recurso, pode ser ignorado... Então podemos passar dados pelo construtor (ainda precisando definir um construtor vazio devido a API do Android), não usando o método `newInstance()`.

Desta forma, os fragments ficam com a seguinte estrutura:
```java
class BlankFragment extends Fragment {

    private Object param1, param2;

    public BlankFragment(){}

    public BlankFragment(Object param1, Object param2){
        this.param1 = param1;
        this.param2 = param2;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        return inflater.inflate(R.layout.fragment_blank, container, false);
    }
}
```

Onde os dados são passados pro viewModel pelo construtor e salvos ou usando dataBinding (a se estudar), ou usando algo como o `onPause()` para ler os valores dos campos. No final do fragment ou em uma transição, os dados do viewModel do fragment podem ser passados para o viewModel da activity, por um método chamado pela transição ou usando o método `public onCleared()`.

**Comment by icarob-eng** [comment]
Resta estudas as transições entre fragments. No momento o app está crashando, o que será resolvido com o uso do viewBinding no adapter.

**Comment by JuliaFreire** [comment]
Link dos atributos do relative layout:

https://developer-android-com.translate.goog/reference/android/widget/RelativeLayout.LayoutParams?hl=pt-br&_x_tr_sl=auto&_x_tr_tl=pt&_x_tr_hl=pt

**Comment by JuliaFreire** [comment]
### Substitution do Edit Text para ImputLayout

Lista para por no recylcer dos Ids do Adapter Carimbo Projeto:

ImputEditText

                  


> android:id="@+id/TextImputEditTextNameProjeto"
> 
>                   android:id="@+id/TextImputEditTextTecnico"
> 
>                   android:id="@+id/TextImputEditTextEmpresa"
> 
>                   android:id="@+id/TextImputEditTextContato"
>                   android:id="@+id/TextImputEditTextCliente"
>                   android:id="@+id/TextImputEditTextLocalObra"
>                   android:id="@+id/TextImputEditTextNúmeroFuros"
>                   android:id="@+id/TextImputEditTextReferenciaNivel"


            

ImputLayout

      TextInputLayoutNameProjeto
      TextInputLayoutTecnico
      TextInputLayouteEmpresa
      TextInputLayoutContato
      TextInputLayoutCliente
      TextInputLayoutLocalObra
      TextInputLayoutNúmeroFuros
      TextInputLayoutReferenciaNivel



Icons 

ic_name_project
ic_technician
ic_empresa
ic_contato
ic_perfil
ic_location
ic_furo
ic_referencia_furo

**Comment by JuliaFreire** [comment]
Padrão do textImputLayout 


Campos Obrigatórios

Nome do Projeto 
Referência de nível
Número de furos

**Comment by JuliaFreire** [comment]
Organizar cor do toolbar no modo noturno @JuliaFreire

**Comment by JuliaFreire** [comment]
Ver video https://youtu.be/uPdnW0Zxmr4 para menu

**Comment by icarob-eng** [comment]
Adaptação para utilização de `ViewBinding` e `Fragment`s:

- [x] `HomeActivity` e seus adapters;
- [x] `CarimboProjetoFragment`;
- [x] `CarimboEnsaioFragment`;
- [x] `EnsaioFragment`;
- [x] `ProjetoFragment` e seus adapters;
- [x] `FuroFragment` e seus adapters;

**Comment by icarob-eng** [comment]
Resta fazer a navegação entre os fragmentos.

**Comment by icarob-eng** [comment]
@JuliaFreire, a estrutura do layout de `ActivitySpt` estava errada, com o `ConstraintLayout` dentro do `FrameLayout`. Já corrigi isto, então veja como o layout ficou.

**Comment by icarob-eng** [comment]
@JuliaFreire, quando for fazer o layout da `ActivitySpt`, veja que o botão com + não precisa ser um `FlaotingActionButton`, mas um botão típico mesmo.

**Comment by icarob-eng** [comment]
Sobre  a navegação e comunicação entre fragmentos: podemos fazer com que todos os fragmentos acessem a um viewModel compartilhado pela activity, assim a comunicação será mais simples, pois é só escrever ou ler os dados no viewModel compartilhado, e quando um fragment pedir uma transação de fragments, o viewModel será responsável por fazê-la.

É possível utilizar tags para fazer a referênciação dos fragments, deste modo, não se faz estritamente necessário o uso do navigation graph da issue #35.

**Comment by JuliaFreire** [comment]
> @JuliaFreire, a estrutura do layout de `ActivitySpt` estava errada, com o `ConstraintLayout` dentro do `FrameLayout`. Já corrigi isto, então veja como o layout ficou.

certo obg

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/199286925-0c719f77-bee6-41a7-895b-3b69355d48c8.png)
   butão de voltar

**Comment by JuliaFreire** [comment]
### Substituir do adpter carimbo projeto


**Substituir Icons**

ic_name_project
ic_technician
ic_empresa
ic_contato
ic_perfil
ic_location
ic_furo
ic_referencia_furo


**Substitua hint**

Nome do Projeto
Técnico responsavél
Empresa ou construtora
Contato
Nome do cliente // ou contratante
Local da obra
Número de furos
Referência de nível // ex: calçada
Altura da referência de nível
![image](https://user-images.githubusercontent.com/89329701/199314291-e1d39204-507d-4e6f-87cb-d4a0abde3801.png)


**Substituir observações**

ImputLayoutNomeProjeto
ImputLayoutNúmeroFuros
ImputLayoutReferenciaNível
ImputLayoutAlturaReferencianível

TODOS ESSES SÃO:  Obrigátorio*

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/199514323-5d3e4528-7af3-4343-8637-46c42c7bdf0a.png)


adicionado menu ao home

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/199523134-aa55c9cf-294b-463c-a047-ea9b111b035c.png)


colocar os itens

**Comment by JuliaFreire** [comment]
1. Por butãos outline
2. Button flutuante outiline
3. menu thema

**Comment by icarob-eng** [comment]
> ### Substituir do adpter carimbo projeto

> **Substitua hint**

Por favor, criar as strings no `strings.xml` para eu colocar aí.

**Comment by icarob-eng** [comment]
@JuliaFreire, os nomes de strings no `strings.xml` não estão devidamente organizados:

Recomendo ver [guia de estilo para strings](https://github.com/Montaigne-ensaios/montaigne_app/blob/main/development_guide.md#2322-strings);

Recomendo que encarregue alguém de corrigir os todos os resources em acordo com o definido no [guia de estilo para resources](https://github.com/Montaigne-ensaios/montaigne_app/blob/main/development_guide.md#232-resources-naming)...

**Comment by icarob-eng** [comment]
Aliás é redundante pôr `Txt` na frente de cada nome de string resource.

**Comment by JuliaFreire** [comment]
- [x] Organizar imputLayout
- [ ] Adicionar butões de interação no menu
- [ ] Organizar strings.xml @Josezinn [Guia de estilo](https://github.com/Montaigne-ensaios/montaigne_app/blob/main/development_guide.md#232-resources-naming)
- [x] Mudar paleta do menu 
- [x] Adicionar butão de tirar fotos de amostras
- [x] Implementar tipo de projeto spt ou granulometria
- [x] Colocar butão de pegar localização  (icon de localização) no _acty carimbo projeto @Josezinn 
- [x] Organizar Adpters ( Colocar o que precisa e padronizar tamanhos)
- [x] Organizar adpter furo melhorar (Paleta de check box exemplo Furo SP01, ver mais informação como prof das amostras ou quantidade)
- [x] Diminuir icon de tela carimbo imageProfile @Josezinn 
- [x] Apagar button flutuante  @Josezinn 
- [x] Tela de ensaio organizar e adicionar icons e tal
- [x] Organizar tela de camadas para implementar
- [x] Colocar TextView para editar nome do projeto em cima dos furos na tela de fragment furo, colocar: Substitua nome do projeto 
Quando acabar tire print e comente marcando icaro. @Josezinn
exemplo image:

![image](https://user-images.githubusercontent.com/89329701/200090700-68827262-6d0f-4d81-8ca1-a04353ad20ed.png)

-[ ] Criar adapter de amostras 

![image](https://user-images.githubusercontent.com/89329701/200092602-7ce49217-30e8-4966-84a3-b3fed50a88ef.png)

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/200148990-63e51d20-265c-4a18-8cd1-66020698cab4.png)



adicionado butão de adicionar amostra na tela fragment ensaio 
@icarob-eng

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/200149427-95cc91ff-7c75-4798-ab7a-cc7a6ecf53fa.png)


alterado adpter projeto

**Comment by JuliaFreire** [comment]
Adicionado adpter furo que contém as amostras o card view não é editavel 
![image](https://user-images.githubusercontent.com/89329701/200151318-954291ad-314d-441b-b5d2-c1356d42b3cc.png)


Implementar na tela fragment furo, irei adicionar a tela de editar amostra

@icarob-eng

**Comment by JuliaFreire** [comment]
TO DO

URGENTE
- [x] Por Butão de alterar tipo de projeto ou tipo de ensaio
- [x] Apagar butão flutuante
- [x] rotação vertical
- [x] Adicionar butões de interação no menu
- [x] Colocar strings dos butões de baixo das telas ( substituir em SPTvm.java)


Importantes porém não urgentes
- [ ] substituir  type do textimput no adpter do codigo
- [ ] organizar hint substituir
- [x] colocar finalziar no menu  
- [x] Organizar menu
- [x] Por titulo na toolbar spt
- [x] Mudar cor dos icons da toolbar(menu)

Altera paleta de cor do menu

**Comment by JuliaFreire** [comment]
@icarob-eng 

_ja adicionado strings, não consiguir alterar o nome la no vm, porque não sei_ 
![image](https://user-images.githubusercontent.com/89329701/203638668-97e74e89-7dfd-4f5a-83df-f5090a602010.png)

**Comment by icarob-eng** [comment]
@JuliaFreire , por favor, corrigir a nomeação de recursos, principalmente as strings para `snake_case`, não `camelCase`, como definido no nosso guia de estilo, coisa que já cobrei de ti.

**Comment by icarob-eng** [comment]
E por favor referenciar de preferência onde o texto da string será usado, não o seu conteúdo...

Eu já corrigi para estas strings específicas, mas espero que ti corrija o resto.

Além disso, não é com `//` que se faz comentários em `.xml`. A sintaxe correta está pelo próprio `strings.xml`... Ti também pode apertar `ctrl` + `/` na linha que quer comentar, que a IDE faz corretamente.

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/204040897-8e760d6d-4b0c-4edd-93ca-a86b6debe1e6.png)
referencia de nivel do projeto e nome de projeto unicos que são obrigatorios

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/204042277-702ab340-4c05-49ca-a4c2-9dbfd1f2fe39.png)
 adicionado toollbar do spt e menu de spt

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/204095437-93938b2c-33d2-47e3-8a00-78d5318815d5.png)


Adicionado icon de voltar no toolbar do spt

**Comment by icarob-eng** [comment]
Solved by #54
