### ISSUE TITLE
Implementação do CRUD

### ISSUE THREAD

**Issue by icarob-eng** [Montaigne-ensaios/montaigne_app#38]
- [x] Cada model vai ter uma classe de `UseCase` que englobe os métodos `save`, `delete`, `update` e `read`;
- [ ] Models como `FuroSPT` e `AmostraSPT` precisarão ser acompanhados de suas classes "superiores" na hora de serem passadas para o `UseCase`;
- [x] O método `read`, que precisa de um listener, será implementado por @icarob-eng;
- [ ] Testar persistência de dados offline;

**Comment by icarob-eng** [comment]
Alterações no Branch #25

**Comment by rodrigoCodDev** [comment]
A questão da leitura(read) vai ficar sob responsabilidade de @icarob-eng 

Diante de nossas(@joao-victor-f  e @rodrigoCodDev ) pesquisas foram testados os seguintes códigos:

```java
// Este foi um teste para leitura de dados do Firebase em outra classe (Falhou)
activity.runOnUiThread(() -> {
    projetoList = ReadProjectsUseCase.execute();
    notifyDataSetChanged();
});
```

```java
// Esta foi uma tentativa de implementar a leitura de projetos com Firebase em uma classe de GUI (Funcionou)

try {
    reference.getDatabase().setPersistenceEnabled(true);
} catch (Exception e) {

}

reference.get().addOnCompleteListener(dataSnapshotProjetoSpt -> {
    for (DataSnapshot child : dataSnapshotProjetoSpt.getResult().getChildren()) {
          ProjetoSpt projeto = child.getValue(ProjetoSpt.class);
          projetoList.add(projeto);
     }

     notifyDataSetChanged();
});
```

Estes códigos foram implementados na classe `ProjetosSalvosAdapter.java`.
Devem ser revistos principalmente para análise de aplicação e possível separação do código da função de leitura para outro arquivo, necessário para manter a arquitetura proposta.

**Comment by icarob-eng** [comment]
Se se utiliza deste trecho de código para o `read` do `usecase`, para quê serve o `read` no Dao?

**Comment by icarob-eng** [comment]
O branch merjado em #39 resolve as demandas desta issue.
