### ISSUE TITLE
Planejamento de testes para o Data Layer

### ISSUE THREAD

**Issue by rodrigoCodDev** [Montaigne-ensaios/montaigne_app#4]
É necessário implementarmos alguns testes no data layer.

Pois, quando estivermos implementando o [data layer](https://developer.android.com/topic/architecture/data-layer), é interessante definir alguns procedimentos de testagem para possamos validar se as operações condizem com o objetivo pelo qual foram planejadas. 

Além disso, a testagem poderá contribuir em velocidade no desenvolvimento do projeto, uma vez que os testes utilizarão de forma minimizada os recursos da [ui layer](https://developer.android.com/topic/architecture/ui-layer) e comprovarão a eficiência das operações para definitiva implementação no aplicativo.

**Comment by rodrigoCodDev** [comment]
Fizemos um mock... Estamos testando.
Precisamos usar JUnit.

**Comment by joao-victor-f** [comment]
Devido ao tempo gasto, à complexidade do desenvolvimento, da falta de materiais de estudo sobre testes unitários do Firebase, e do uso da interface gráfica como principal ferramenta de testes, a issue será fechada como won't fix.
