### ISSUE TITLE
Exceção em onCreate EnsaioActivity

### ISSUE THREAD

**Issue by marmundo** [Montaigne-ensaios/montaigne_app#42]
Esse código só funciona se EnsaioActivity for Intent de Amostra adapter.

`  int idFuro = (int) getIntent().getExtras().get("idFuro");
        int idAmostra = (int) getIntent().getExtras().get("idAmostra");
        ProjetoSpt projetoSpt = (ProjetoSpt) getIntent().getExtras().get("projetoSpt");`

Só que EnsaioActivity também é chamado por CarimboUnicoVM que não passa esses extras.

Eu acho que terá que ter outra activity para o CarimboUnicoVM.

O que você acha?

**Comment by icarob-eng** [comment]
Tem que gerar esses valores se forem vazios.

**Comment by marmundo** [comment]
mas qual seria os valores se nao existe amostra ainda? 

Eu não acho legal colocar esse valores diretamente. É bom usar um enum para padronizar e diminuir o risco de ter erro de nomes sendo passado nos extras das intents.

```
public enum AwesomeEnum {
  SOMETHING, OTHER;
}

intent.putExtra("AwesomeEnum", AwesomeEnum.SOMETHING);

AwesomeEnum result = (AwesomeEnum) intent.getSerializableExtra("AwesomeEnum");
```

Ou usando uma classe utilitária

```
// Constant utility class
package com.effectivejava.science;
public class PhysicalConstants {
    private PhysicalConstants() { }  // Prevents instantiation

    public static final double AVOGADROS_NUMBER   = 6.02214199e23;
    public static final double BOLTZMANN_CONSTANT = 1.3806503e-23;
    public static final double ELECTRON_MASS      = 9.10938188e-31;
}
```

**Comment by icarob-eng** [comment]
Uma enum para padronizar as chaves dos campos passados?

**Comment by marmundo** [comment]
> Uma enum para padronizar as chaves dos campos passados?

sim ou uma classe de constantes como a strings.xml.

Assim evita estes erros de passagem de chave.

Outra coisa, quais serão os valores padrão?

Eu adicionei um tratamento de exceção pro nullpoint. Dentro do catch vc adiciona os valores padrão.

**Comment by icarob-eng** [comment]
Eu tinha pensado nisso na #26, mas acredito que a transferência de dados vai ficar melhor quando mudarmos pros fragments, se não me engano, estes dados podem ser passados num construtor ou ao menos um método que configure tudo, assim a activity passaria os dados necessários pro fragment e eles serias exigidos nos parâmetros e pa.

**Comment by marmundo** [comment]
> Eu tinha pensado nisso na #26, mas acredito que a transferência de dados vai ficar melhor quando mudarmos pros fragments, se não me engano, estes dados podem ser passados num construtor ou ao menos um método que configure tudo, assim a activity passaria os dados necessários pro fragment e eles serias exigidos nos parâmetros e pa.

ok. pois vamos deixar aberto para resolver isso depois com essa sua abordagem.

**Comment by rodrigoCodDev** [comment]
Tava quebrando quando ia criar o projeto e passar pra tela de ensaio.
Analisei aqui o caso, modifiquei algumas coisas e tirei aquela estrutura antiga do mock do carimbo único.

Precisamos de um método lá no usecase de projeto para leitura especifica de um projeto por meio do Id. Isto é necessário porque as operações dos usecase se baseiam no objeto do projeto para fazer as modificações no banco de dados, logo, se ele estiver desatualizado, poderá ocasionar alguns erros a implementação.

Seria viável retornar o objeto do projeto modificado nos usecases?
Poderia até funcionar, mas como iremos tratar ver se consiguimos tratar algum tipo de exceção em relação ao Firebase, seria bom mantermos um método separado para atualização própria de um projeto SPT especifico.

Sobre os dados que estão sendo passados na intent do carimbo unico para a tela de nova amostra, é um caso a se *analizar com cuidado*, acho que o problema não é ele receber um objeto nulo, mas sim implementar algumas funções no programa tentando utilizar este objeto nulo. (Bom, é só uma visão, ainda não parei para consertar esta parte e ver direito o exception)

Isso aliás, retoma muito do que utilizei em meu projeto Compiti, um aplicativo de criação de tarefas e anotações. Lá, na tela de preenchimento dessas anotações, recebia-se também um objeto Task e ele era usado como referencia para saber se era uma nova tarefa que estava sendo criada ou era uma atualização.

Como isso é possível?
Testa-se se o valor presente no objeto recebido no intent é nulo. Se ele for nulo, é uma nova tarefa, senão, é uma atualização.

De qualquer forma, é só uma ideia de como é que isso pode ser implementado, podemos discutir e testar isso melhor pessoalmente, talvez os Enums sugeridos também funcionem.

Fiz as alterações e coloquei numa branch separada, a `#42-conserts` . Mesmo não participando dessa issue, entendi que era para resolver algo nesse sentido com @marmundo ontem mais cedo.

Está funcional?
Não, é apenas um começo de resolução para o problema visto ontem mais cedo. Precisamos, justamente, vermos como fazer esse read e como vamos relacionar os usecases com a inteface gráfica.

**Comment by icarob-eng** [comment]
Problema resolvido com as mudanças para fragments.
