### ISSUE TITLE
Layouts de granulometria

### ISSUE THREAD

**Issue by icarob-eng** [Montaigne-ensaios/montaigne_app#53]
Transferir layouts de granulometria do Figma para o AS. Os layouts devem ser criados com fragments e não se precisa criar os respectivos arquivos Java. Precisa-se de apenas um layout de activity, que irá hospedar todas os fragments, entitulado `activity_granulometria.xml`, com botões de navegação e um `androidx.fragment.app.FragmentContainerView` que servirá de frame para os fragments. Ver `activity_spt.xml` para referência.

Por favor listar as telas que serão criadas aqui e, por cima, o papel de cada uma. Também deve-se criar um navigation graph para a activity. Em caso de dúvidas posso ajudar com esta parte.

**Comment by JuliaFreire** [comment]
**Criação de adpter** 

- [x] Adpter de dados graudo e miudo
- [x] Adpter de dados da peneira

**Comment by JuliaFreire** [comment]
Criar lista de hint (exemplos)  do adpter dados do agregado

@nicoled20 

![image](https://user-images.githubusercontent.com/89329701/216043812-dd9f1b39-1060-43b9-9679-3331b0ed9798.png)

**Comment by JuliaFreire** [comment]
organizar os ids das seguintes telas 

**Peneiras graudos e peneiras miudo**
![image](https://user-images.githubusercontent.com/89329701/216044490-8db9552e-2a5d-4b5a-8430-655ca5eec37b.png)


**dados agregados**
![image](https://user-images.githubusercontent.com/89329701/216044802-401b50ce-fd82-4ecb-8e63-c6c5ce38c672.png)

**Comment by JuliaFreire** [comment]
ERRO @Josezinn @icarob-eng 

BLANK FRAGMENT      

![image](https://user-images.githubusercontent.com/89329701/216045368-f55c38c0-54f3-4af6-8c93-eaf73fda66bf.png)

**Comment by nicoled20** [comment]
Lista de exemplos: 

Ex: Areia concreto

Ex: 1000g

Ex: Amostra de areia 1

Ex: Amostra de areia 2

Ex: xx/xx/xx

**Comment by nicoled20** [comment]
Tela peneiras graúdo

checkboxn76mm
checkboxn38mm
checkboxn19mm
checkboxn95mm
checkboxn48mm
checkboxn24mm
checkboxn12mm
checkboxn06mm
checkboxn03mm
checkboxn015mm

checkboxi64mm
checkboxi50mm
checkboxi32mm
checkboxi25mm
checkboxi125mm
checkboxi63mm

**Comment by nicoled20** [comment]
Tela peneiras miúdo

checkboxmiudo48mm
checkboxmiudo24mm
checkboxmiudo12mm
checkboxmiudo06mm
checkboxmiudo03mm
checkboxmiudo015mm
