### ISSUE TITLE
Ajustes do Layout

### ISSUE THREAD

**Issue by JuliaFreire** [Montaigne-ensaios/montaigne_app#67]

**Comment by JuliaFreire** [comment]
**AJUSTES GERAL**


- [x] Adicionar opção de novo projeto granulometria ou spt no menu home

- [x] Ajeitar fragment da tela carimbo projeto e icon de foto 
erro :
![image](https://user-images.githubusercontent.com/89329701/215563873-8bf978c7-1689-4277-826e-2a6051f0ac5c.png)

- [ ] Adicionar text view no icon de foto de amostra - tela ensaio
![image](https://user-images.githubusercontent.com/89329701/215566322-6704ecbd-b6e4-4ef4-957c-80dea404ea07.png)

- [x] Apagar text view 
![image](https://user-images.githubusercontent.com/89329701/215566504-34254cc6-3cb3-4a78-82a0-6f4ca4dab0a8.png)


**INTERFACE**

- [ ] Menu icon colocar branco 
- [ ] Seta voltar branco
- [x] Icon de telefone na tela carimbo projeto muito grande 


**MENU**

- [x] Adicionar projeto em menu home opção
- [x] Ajeitar texto do menu spt de novo furo 
- [x] Aparecer titulo da toolbar spt

**Comment by JuliaFreire** [comment]
TEMAS 

- [x] Organizar adpter carimbo projeto tema escuro
![image](https://user-images.githubusercontent.com/89329701/215832284-f4000381-4edd-4df3-8a64-2054cb8d3d8c.png)

- [x] String do imputlayout nivel do furo n

![image](https://user-images.githubusercontent.com/89329701/215832336-3ffef93d-69ca-484e-9f34-7f960b4a26c2.png)

- [x] Mudar cor do icon filtro e a cor do icon check box
![image](https://user-images.githubusercontent.com/89329701/215832870-ffa6ab83-7090-4a1b-86d8-be6c342694f2.png)

- [x] Alterar cor do icon add projeto para visualizar no tema claro 
![image](https://user-images.githubusercontent.com/89329701/215833489-33cfb0a3-6a2c-47bb-bb00-b1988cdf9c38.png)

- [ ] Alterar icon do app

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/215835616-caa704ce-b77e-427d-8e95-41bcdb08723e.png)


Alterar id das novas opções de adicionar projeto granulometria e spt

@icarob-eng

**Comment by JuliaFreire** [comment]
**REALIZADO** 
- [x] Adicionar opção de novo projeto granulometria ou spt no menu home

![image](https://user-images.githubusercontent.com/89329701/215836142-21e84959-eb49-433b-996c-c782d28e84bc.png)


- [x]  alterado icon de foto do carimbo projeto
![image](https://user-images.githubusercontent.com/89329701/215844685-f408ab68-92e9-43fa-b486-0657ed8842b6.png)

**Comment by JuliaFreire** [comment]
- [x] Alterar cor de icon para vermelho
![image](https://user-images.githubusercontent.com/89329701/215838785-7ed01c56-37dd-4f65-9728-2cb40cdcfaa5.png)

**Comment by JuliaFreire** [comment]
![image](https://user-images.githubusercontent.com/89329701/215858439-4191b165-7044-4b06-9c25-2c7610414ad8.png)



apagado text view do adpter ProjetosSalvosAdapter, alterado tema do fundo dos card view

**Comment by JuliaFreire** [comment]
Granulometria

**Comment by icarob-eng** [comment]
Espaço para novas ids de actions adicionado (ações em si não implementadas).

**Comment by icarob-eng** [comment]
- [x] Bloquear rotação de tela;

**Comment by icarob-eng** [comment]
- [x] Atualizar recycler de categorias de projetos na home activity;

**Comment by JuliaFreire** [comment]
- [x] Ajeitar erro @icarob-eng 

![image](https://user-images.githubusercontent.com/89329701/217941610-61a1b6e4-d8eb-4db4-ab5f-531af5c8c376.png)
